TebLocalPlannerROS:

  map_frame: map
  odom_frame: odom
  transform_tolerance: 0.5    
  # Trajectory
    
  teb_autosize: True                            # Mantieni True per consentire al planner di adattare automaticamente la dimensione della traiettoria
  dt_ref: 0.3 #0.2                              # intervallo di tempo di riferimento in cui la traiettoria viene campionata [s]
  dt_hysteresis: 0.1 #0.1                       # intervallo di tempo aggiuntivo per la pianificazione della traiettoria [s]
  global_plan_overwrite_orientation: True 
  max_global_plan_lookahead_dist: 3.0 #2.0      # massima distanza di ricerca del piano globale [m]
  feasibility_check_no_poses: 5                 # numero di pose successive da controllare per la fattibilità
                                                #(Puoi aumentarlo se vuoi un controllo di fattibilità più rigoroso)
  # Robot
          
  max_vel_x: 0.25 #0.25                         # velocità massima lungo l'asse x [rad/s]
  max_vel_x_backwards: 0.5 #0.2               # velocità massima all'indietro lungo l'asse x [rad/s]
  max_vel_theta: 5.0 #0.5                     # velocità angolare massima [rad/s]
  acc_lim_x: 0.2 # 0.2                         # accelerazione massima lungo l'asse x [rad/s^2]
  acc_lim_theta: 0.6283 #0.5, 0.26            # accelerazione angolare massima [rad/s^2]
  min_turning_radius: 0.0                     # turning radius [m] (car-like robots) (0.0: non-omnidirectional)
  footprint_model: # types: "point", "circular", "two_circles", "line", "polygon"
    type: "polygon" #"circular" 
    vertices: [[0.225, -0.35], [-0.225, -0.35], [-0.225, 0.35], [0.225, 0.35]] # for type "polygon"
    

  # GoalTolerance
      
  xy_goal_tolerance: 0.3 #0.2                 # tolleranza sulla posizione del goal [m]
  yaw_goal_tolerance: 0.1571                  # tolleranza sull'orientamento del goal [rad]
  free_goal_vel: False                        # se True, il robot può raggiungere il goal con una velocità non nulla
                                              #(per evitare che il robot si muova liberamente una volta raggiunto l'obiettivo)
  # Obstacles
      
  min_obstacle_dist: 0.05                     # distanza minima dall'ostacolo [m]
  inflation_dist: 0.0                        # distanza di inflazione dell'ostacolo [m]
  dynamic_obstacle_inflation_dist: 0.1       # distanza di inflazione dell'ostacolo dinamico [m]
  include_costmap_obstacles: True            # se True, considera gli ostacoli della mappa di costo
  costmap_obstacles_behind_robot_dist: 0.1   # distanza minima dall'ostacolo alla posizione attuale del robot [m]
  obstacle_poses_affected: 25 #30            # numero di pose successive da considerare per l'interazione con gli ostacoli
  costmap_converter_plugin: ""               # plugin per convertire la mappa di costo in ostacoli
  costmap_converter_spin_thread: True        # se True, esegui il plugin in un thread separato
  costmap_converter_rate: 5                  # frequenza di aggiornamento del plugin [Hz]

  # Optimization
      
  no_inner_iterations: 5 #5                  # numero di iterazioni per la minimizzazione interna
  no_outer_iterations: 4 #4         
  optimization_activate: True
  optimization_verbose: False 
  penalty_epsilon: 0.1                       # valore epsilon per la penalizzazione della distanza dall'ostacolo
  weight_max_vel_x: 1 #2                     # peso per la velocità massima lungo l'asse x
  weight_max_vel_theta: 1 #1                 # peso per la velocità angolare massima
  weight_acc_lim_x: 0.5 # 1 
  weight_acc_lim_theta: 1 # 1
  weight_kinematics_nh: 1000 #1000
  weight_kinematics_forward_drive: 100000 #1000 #1000000             # Aumenta il peso per penalizzare il movimento all'indietro
  weight_kinematics_turning_radius: 1 #1 #only for car-like robots
  weight_optimaltime: 5.0 #1
  weight_obstacle: 75 #50
  weight_viapoint: 5.0 #5.0 #1.0
  weight_inflation: 0.1 #0.1
  weight_dynamic_obstacle: 10 # not in use yet
  selection_alternative_time_cost: False # not in use yet

  # Homotopy Class Planner

  enable_homotopy_class_planning: False #True
  enable_multithreading: True
  simple_exploration: False
  max_number_classes: 2 #4
  roadmap_graph_no_samples: 15
  roadmap_graph_area_width: 5
  h_signature_prescaler: 0.5
  h_signature_threshold: 0.1
  obstacle_keypoint_offset: 0.1
  obstacle_heading_threshold: 0.45
  visualize_hc_graph: False

  #ViaPoints
  global_plan_viapoint_sep: 0.5 #negative if none
  via_points_ordered: False #adhere to order of via points

  #Feedback
  publish_feedback: true #false