footprint: [[0.225, -0.35], [-0.225, -0.35], [-0.225, 0.35], [0.225, 0.35]]
inflation_radius: 0.39
footprint_padding: 0.02  # Add this line to specify the padding around the footprint
robot_base_frame: base_link # Add this line to specify the robot base frame
update_frequency: 4.0
publish_frequency: 3.0
resolution: 0.05 
transform_tolerance: 0.5  # Add this line to specify the transform tolerance
obstacle_range: 2.5 # Add this line to specify the obstacle range
raytrace_range: 8.0 # Add this line to specify the raytrace range
max_obstacle_height: 1.0
min_obstacle_height: 0.05
robot_radius: 0.35

observation_sources: laser_scan_sensor 

# laser_scan_sensor: {sensor_frame: scan, data_type: LaserScan, topic: scan_merged, marking: true, clearing: true}
laser_scan_sensor: {sensor_frame: scan, data_type: LaserScan, topic: scan, marking: true, clearing: true}

