local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 10.0
  publish_frequency: 10.0
  rolling_window: true
  width: 6.0
  height: 6.0
  resolution: 0.05
  observation_persistence: 0.0
  static_map: false        # Nessuna mappa statica per la costmap locale
  cost_scaling_factor: 4.0 # Abbassa se vuoi permettere al robot di avvicinarsi di più agli ostacoli


  plugins:
  - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}  # Usa i dati dinamici dei sensori
  - {name: inflation_layer, type: "costmap_2d::InflationLayer"}  # Aggiunge inflazione intorno agli ostacoli

  obstacle_layer:
    max_obstacle_height: 1.0
    min_obstacle_height: 0.1
    observation_sources: laser_scan_sensor
    laser_scan_sensor: {sensor_frame: scan, data_type: LaserScan, topic: scan, marking: true, clearing: true}

  inflation_layer:
    inflation_radius: 0.2
    cost_scaling_factor: 10.0