recovery_behaviors:
  - name: 'clear_costmap'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'
  - name: 'rotate_recovery'
    type: 'rotate_recovery/RotateRecovery'

clear_costmap_recovery:
  reset_distance: 3.0  # Distanza di reset per la mappa di costo

rotate_recovery:
  max_rotational_vel: 1.0  # Velocità rotazionale massima
  min_rotational_vel: 0.4  # Velocità rotazionale minima
  acc_lim_th: 3.2  # Accelerazione angolare massima
  tolerance: 0.1  # Tolleranza per il recupero
  frequency: 20.0  # Frequenza di esecuzione del recupero